# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171027_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(default=False, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='urls',
            field=models.BooleanField(default=False),
        ),
    ]
